### ISSUE TITLE
I think update the README.md file to make the code more  understandable 

### ISSUE THREAD

**Issue by ferid333** [BorisDundakov/PythonAutomation2#1]
I think update the README.md file to make the code more  understandable

**Comment by BorisDundakov** [comment]
Hi, thanks for the suggestion.
I will look into in the coming days :)

**Comment by BorisDundakov** [comment]
Updated the README file with this PR: https://github.com/BorisDundakov/PythonAutomation2/pull/2

**Comment by ferid333** [comment]
You are welcome
